[default]
SQLALCHEMY_TRACK_MODIFICATIONS=0
SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:postgres@localhost/Integrada'
SECRET_KEY = 'e7c0596d00d6d1d17e64d6547cd732cf'
EXTENSIONS=[
    'estoque.blueprints.view',
    'estoque.extensions.serializer',
    'estoque.extensions.database'
]